// Code generated by go generate; DO NOT EDIT.
// This Zoho CRM endpoint API was generated @ 2019-10-08 22:29:14.0932216 -0600 CST m=+0.010737501
package crm

import (
	"fmt"

	zoho "github.com/schmorrison/Zoho"
)

// GetModules returns the list of modules available in the CRM account
// https://www.zoho.com/crm/help/api/v2/#Modules-APIs
func (c *API) GetModules() (data ModulesResponse, err error) {
	endpoint := zoho.Endpoint{
		Name:         "modules",
		URL:          fmt.Sprintf("https://www.zohoapis.%s/crm/v2/settings/modules", c.ZohoTLD),
		Method:       zoho.HTTPGet,
		ResponseData: &ModulesResponse{},
	}

	err = c.Zoho.HTTPRequest(&endpoint)
	if err != nil {
		return ModulesResponse{}, fmt.Errorf("Failed to retrieve modules: %s", err)
	}

	if v, ok := endpoint.ResponseData.(*ModulesResponse); ok {
		return *v, nil
	}

	return ModulesResponse{}, fmt.Errorf("Data returned was not 'ModulesResponse'")
}

type ModulesResponse struct {
	Modules []struct {
		APIName       string `json:"api_name,omitempty"`
		APISupported  bool   `json:"api_supported,omitempty"`
		Convertable   bool   `json:"convertable,omitempty"`
		Createable    bool   `json:"createable,omitempty"`
		Deletable     bool   `json:"deletable,omitempty"`
		Editable      bool   `json:"editable,omitempty"`
		GeneratedType string `json:"generated_type,omitempty"`
		ID            string `json:"id,omitempty"`
		ModifiedBy    struct {
			ID   string `json:"id,omitempty"`
			Name string `json:"name,omitempty"`
		} `json:"modified_by,omitempty"`
		ModifiedTime  string      `json:"modified_time,omitempty"`
		ModuleName    string      `json:"module_name,omitempty"`
		PluralLabel   string      `json:"plural_label,omitempty"`
		SingularLabel string      `json:"singular_label,omitempty"`
		Viewable      bool        `json:"viewable,omitempty"`
		WebLink       interface{} `json:"web_link,omitempty"`
	} `json:"modules,omitempty"`
}
